const { faker } = require('@faker-js/faker');
/**

*/
class RandomGenerator {

  /**
   * @method randomNameTask
   * @return {string} - return a random name task with the following structure:
   * task-(random name task )
   * 
   * @example
   * task-John Doe
   */
  randomNameTask() {
    this.task = "task-" + faker.person.fullName();
    return this.task;
  }

  /**
   * @method randomDescriptionTask
   * @return {string} -return a random description task with the following structure:
   * task for the company: (random name company)
   * @example
   * task for the company: Weber - Stehr
   */
  randomDescriptionTask() {
    this.task = "task for the company: " + faker.company.name();
    return this.task;
  }
  
  /**
   * @method randomNameSpace
   * @return {string} - return a random space name with the following structure:
   * space-(random name space )
   */
  randomNameSpace() {
    this.space = "Space " + faker.string.alphanumeric({ length: { min: 2, max: 5 } });
    return this.space;
  }

  /**
   * @method randomIdTask
   * @return {string} -return a random alphanumeric.
   * @example
   * 'muaApG'
   */
  randomIdTask(){
    return faker.string.alphanumeric({ length: { min: 5, max: 10 } })
  }

  /**
   * @returns {string}
   */

  /**
 * The function generates a random name list by concatenating a noun generated by the faker library
 * with the current timestamp.
 * @returns The function `randomNameList()` returns a string that is a concatenation of a randomly
 * generated noun using the `faker.word.noun()` function and the current timestamp obtained using
 * `Date.now()`.
 */
  randomNameList() {
    this.list = faker.word.noun() + Date.now();
    return this.list
  }
  /**
 * De randomNameFolder() generates a randmon folder name that contains the current timestamp
 * @returns a string 'faker.music.gener()' and the current timestamp 'Data.now()'
 */
  randomNameFolder() {
    this.folder = faker.music.genre() + Date.now();
    return this.folder
  }

  /**
 * The function generates a unique name by combining a random noun with the current timestamp.
 * @returns a string that is a combination of a randomly generated noun from the faker library and the
 * current timestamp.
 */
  name() {
    const nameList = faker.word.noun() + Date.now();
    return nameList
  }
  /**
   * @returns return a empty string.
   */
  empty() {
    return ""
  }

  /**
   * Executes a method of RandomGenerator class 
   * @param {*} string - method to be executed it should be a string with the following structure:
   * (name method)
   * @returns - the result of the method that was executed 
   * @example
   * randomHandler("(randomNameTask)")
   */
  randomHandler(string) {
    let value = string
    if (string.startsWith("(")) {
      const method = string.replace(/[()]/g, "");
      value = this[method]();
    }
    return value
  }
}

module.exports = new RandomGenerator();
